package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int catId;
     private String catName;

    public Category(String catName) {
        this.catName = catName;
    }

    public Category() {
    }

	
    public Category(int catId) {
        this.catId = catId;
    }
    public Category(int catId, String catName) {
       this.catId = catId;
       this.catName = catName;
    }
   
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }




}


