package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer proId;
     private String proName;
     private int suplierId;
     private int catId;
     private double proPrice;
     private int stock;
     private String productcol;

    public Product(Integer proId, String proName, int suplierId, int catId, double proPrice, int stock, String productcol) {
        this.proId = proId;
        this.proName = proName;
        this.suplierId = suplierId;
        this.catId = catId;
        this.proPrice = proPrice;
        this.stock = stock;
        this.productcol = productcol;
    }

    public Product() {
    }

    public Product(String proName, int suplierId, int catId, double proPrice, int stock, String productcol) {
       this.proName = proName;
       this.suplierId = suplierId;
       this.catId = catId;
       this.proPrice = proPrice;
       this.stock = stock;
       this.productcol = productcol;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public int getSuplierId() {
        return this.suplierId;
    }
    
    public void setSuplierId(int suplierId) {
        this.suplierId = suplierId;
    }
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public double getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(double proPrice) {
        this.proPrice = proPrice;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getProductcol() {
        return this.productcol;
    }
    
    public void setProductcol(String productcol) {
        this.productcol = productcol;
    }




}


