package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Purchases generated by hbm2java
 */
public class Purchases  implements java.io.Serializable {


     private Integer purId;
     private Integer proId;
     private String proName;
     private String suplierName;
     private String serialNumber;
     private String catName;
     private Date purDate;
     private Integer stock;
     private Double purPrice;
     private String remarks;
   

    public Purchases() {
    }

    public Purchases(Integer purId, Integer proId, String proName, String suplierName, String serialNumber, String catName, Date purDate, Integer stock, Double purPrice, String remarks) {
        this.purId = purId;
        this.proId = proId;
        this.proName = proName;
        this.suplierName = suplierName;
        this.serialNumber = serialNumber;
        this.catName = catName;
        this.purDate = purDate;
        this.stock = stock;
        this.purPrice = purPrice;
        this.remarks = remarks;
    }

    
    public Integer getPurId() {
        return this.purId;
    }
    
    public void setPurId(Integer purId) {
        this.purId = purId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getSuplierName() {
        return this.suplierName;
    }
    
    public void setSuplierName(String suplierName) {
        this.suplierName = suplierName;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Date getPurDate() {
        return this.purDate;
    }
    
    public void setPurDate(Date purDate) {
        this.purDate = purDate;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Double getPurPrice() {
        return this.purPrice;
    }
    
    public void setPurPrice(Double purPrice) {
        this.purPrice = purPrice;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


