package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PurchasesCost generated by hbm2java
 */
public class PurchasesCost  implements java.io.Serializable {


     private Integer costId;
     private Integer representiveId;
     private String costName;
     private String costType;
     private String costValue;
     private Date costDate;

    public PurchasesCost(Integer costId, Integer representiveId, String costName, String costType, String costValue, Date costDate) {
        this.costId = costId;
        this.representiveId = representiveId;
        this.costName = costName;
        this.costType = costType;
        this.costValue = costValue;
        this.costDate = costDate;
    }

    public PurchasesCost() {
    }

    

   
   
    public Integer getCostId() {
        return this.costId;
    }
    
    public void setCostId(Integer costId) {
        this.costId = costId;
    }
    public String getCostName() {
        return this.costName;
    }
    
    public void setCostName(String costName) {
        this.costName = costName;
    }
    public String getCostType() {
        return this.costType;
    }
    
    public void setCostType(String costType) {
        this.costType = costType;
    }
    public String getCostValue() {
        return this.costValue;
    }
    
    public void setCostValue(String costValue) {
        this.costValue = costValue;
    }
    public Date getCostDate() {
        return this.costDate;
    }
    
    public void setCostDate(Date costDate) {
        this.costDate = costDate;
    }

    public Integer getRepresentiveId() {
        return representiveId;
    }

    public void setRepresentiveId(Integer representiveId) {
        this.representiveId = representiveId;
    }




}


