package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Return generated by hbm2java
 */
public class Return  implements java.io.Serializable {


     private int returnId;
     private Integer repId;
     private String repName;
     private Integer proId;
     private String proName;
     private Integer stock;
     private Date date;

    public Return() {
    }

	
    public Return(int returnId) {
        this.returnId = returnId;
    }
    public Return(int returnId, Integer repId, String repName, Integer proId, String proName, Integer stock, Date date) {
       this.returnId = returnId;
       this.repId = repId;
       this.repName = repName;
       this.proId = proId;
       this.proName = proName;
       this.stock = stock;
       this.date = date;
    }
   
    public int getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(int returnId) {
        this.returnId = returnId;
    }
    public Integer getRepId() {
        return this.repId;
    }
    
    public void setRepId(Integer repId) {
        this.repId = repId;
    }
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
   



}


