package com.bexpress.pojo;
// Generated Jul 23, 2016 4:01:06 PM by Hibernate Tools 4.3.1



/**
 * Supervisor generated by hbm2java
 */
public class Supervisor  implements java.io.Serializable {


     private int supId;
     private String supName;
     private String managerId;
     private String comId;
     private String area;

    public Supervisor() {
    }

	
    public Supervisor(int supId) {
        this.supId = supId;
    }
    public Supervisor(int supId, String supName, String managerId, String comId, String area) {
       this.supId = supId;
       this.supName = supName;
       this.managerId = managerId;
       this.comId = comId;
       this.area = area;
    }
   
    public int getSupId() {
        return this.supId;
    }
    
    public void setSupId(int supId) {
        this.supId = supId;
    }
    public String getSupName() {
        return this.supName;
    }
    
    public void setSupName(String supName) {
        this.supName = supName;
    }
    public String getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }
    public String getComId() {
        return this.comId;
    }
    
    public void setComId(String comId) {
        this.comId = comId;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }




}


